export { Footer } from './Footer';
export { Header } from './Header';
export { Home } from './Home';
export { stepOne } from './stepOne'
export { stepTwo } from './stepTwo'
export { stepThree } from './stepThree'
export { stepFour } from './stepFour'
export { Crowdsale } from './crowdsale'
export { Invest } from './invest'
export { Manage } from './manage'
